<a href="https://colab.research.google.com/github/ChingizIbnVaxob/data-science-practices/blob/main/18.01.24/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [5]:
x = np.array([2.,4.,6.,1.,8.,0.,7.,5.])
x

array([2., 4., 6., 1., 8., 0., 7., 5.])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [15]:
y = np.zeros((9,9))
print(y)
np.size(y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


81

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [17]:
help(np.add) #np.info(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [22]:
vector = np.zeros(12)
vector[5]=1
vector

array(12)

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [24]:
x7 = np.arange(20,60,1)
x7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [25]:
x7[::-1]

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [29]:
x9 = np.arange(12,21).reshape(3,3)
x9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [31]:
np.nonzero([3, 7, 0, 0, 9, 0])

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [39]:
x11 = np.random.rand(2,2,2)
x11

array([[[0.08567945, 0.2504201 ],
        [0.06941021, 0.74009711]],

       [[0.38685489, 0.3664852 ],
        [0.29753584, 0.76366861]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [44]:
x12 = np.random.rand(9,9)
print(f"x12 : {x12}\nmin: {np.min(x12)} \nmax: {np.max(x12)}")

x12 : [[0.93520181 0.92304433 0.64940263 0.03683358 0.92012836 0.53138813
  0.52705779 0.98468243 0.47949245]
 [0.82518266 0.42006813 0.40710291 0.20404545 0.37177522 0.31444527
  0.95408109 0.25393256 0.5276866 ]
 [0.3863043  0.60052616 0.9437056  0.38535227 0.62997167 0.92236521
  0.86915845 0.59282678 0.28384769]
 [0.34193112 0.38308913 0.79478853 0.92410829 0.84433431 0.83346551
  0.01387599 0.41465588 0.32609484]
 [0.03153915 0.76462981 0.10766452 0.21852443 0.53745887 0.86215918
  0.49531749 0.08542478 0.21252808]
 [0.98159699 0.31974772 0.87239321 0.51161005 0.39941407 0.15273313
  0.1935209  0.77361023 0.01207942]
 [0.1050847  0.05899169 0.9616578  0.55372853 0.48322534 0.71805685
  0.25474381 0.78226263 0.15891345]
 [0.28778917 0.94050588 0.6864771  0.12756734 0.35544768 0.95351377
  0.88117402 0.16260892 0.17562116]
 [0.70575007 0.0780635  0.99210401 0.81441118 0.88902591 0.78977886
  0.24543539 0.28720125 0.94786689]]
min: 0.012079419690935178 
max: 0.9921040107493989


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [46]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
np.nan in set([np.nan]),
0.7 == 7 * 0.1)

nan False False nan True False


#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [56]:
x43 = np.ones((4,3))
x34 = np.ones((3,4))
print(f"4x3 : \n{x43}\n3x4 : \n{x34}\nMultiply: \n{x43.dot(x34)}")

4x3 : 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3x4 : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Multiply: 
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [61]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [62]:
a = np.array([1, 2])
b = np.array([4, 5])

print (a>b)
print (a>=b)
print (a<b)
print (a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [67]:
x171 = np.array(0) / np.array(0)
x172 = np.array(0) // np.array(0)
x173 = np.array([np.nan]).astype(int).astype(float)

print(x171, x172, x173)

nan 0 [-9.22337204e+18]


<ipython-input-67-8ea53c38025f>:1: RuntimeWarning: invalid value encountered in divide
  x171 = np.array(0) / np.array(0)
<ipython-input-67-8ea53c38025f>:2: RuntimeWarning: divide by zero encountered in floor_divide
  x172 = np.array(0) // np.array(0)


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [76]:
x181 = np.arange(0,31, 2)
x182 = np.arange(0,31, 3)
print(x181,"\n",x182,"\n",np.intersect1d(x182, x181))


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30] 
 [ 0  3  6  9 12 15 18 21 24 27 30] 
 [ 0  6 12 18 24 30]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [94]:
x19 = np.random.randn(10)
print(x19)
x = x19[x19>=0]
np.floor(x)

[ 0.09568927 -0.32036214  1.82773755 -0.43025927  2.29195403  1.32617635
 -1.1698686   0.26687281  0.05982662 -0.1605465 ]


array([0., 1., 2., 1., 0., 0.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [101]:
np.arange(0, 1.8, 0.2).reshape((3,3))

array([[0. , 0.2, 0.4],
       [0.6, 0.8, 1. ],
       [1.2, 1.4, 1.6]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [108]:
x = np.random.randn(10)
np.sort(x)

array([-1.50788406, -0.81524883, -0.68053239, -0.55810287, -0.38746233,
        0.03182331,  0.19604182,  0.29848317,  0.37630718,  1.00380732])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [109]:
A = np.random.randn(8)
B = np.random.randn(8)


print(np.allclose(A, B))
print(np.array_equal(A, B))

False
False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [113]:
import numpy as np

matritsa1 = np.random.rand(6, 3)

matritsa2 = np.random.rand(3, 4)

natija = np.dot(matritsa1, matritsa2)

print("(6x3):")
print(matritsa1)
print("\n(3x4):")
print(matritsa2)
print("\n(6x4):")
print(natija)

(6x3):
[[0.25508259 0.47477442 0.43939367]
 [0.17592578 0.59496867 0.05863852]
 [0.63094049 0.83520303 0.89455809]
 [0.13498508 0.42885451 0.09673045]
 [0.56020937 0.79202691 0.60496   ]
 [0.12779854 0.50522239 0.43230794]]

(3x4):
[[0.143621   0.40953912 0.92704739 0.99901831]
 [0.23734522 0.59798172 0.09070288 0.04729536]
 [0.68398999 0.99348874 0.3275226  0.79041259]]

(6x4):
[[0.44986153 0.8249054  0.42344842 0.6245891 ]
 [0.20658776 0.48608559 0.23626234 0.25024095]
 [0.90071653 1.64656436 0.95365504 1.37689231]
 [0.18733592 0.40782944 0.19571731 0.23159236]
 [0.68222821 1.30406622 0.78931783 1.07528662]
 [0.43396098 0.78394533 0.30589104 0.4932694 ]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [119]:
v = np.random.randn(5)
print(f"before :\n{v}")
max_index = np.argmax(v)
v[max_index] = 0

print(f"after :\n{v}")

before :
[-1.033594   -1.29147381  0.32549256 -0.05376737 -0.7376444 ]
after :
[-1.033594   -1.29147381  0.         -0.05376737 -0.7376444 ]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [138]:
import numpy as np
import datetime
z=datetime.datetime.now().date()
c = np.datetime64(z)
print(f"yestarday: {c-1}\ntoday : {c}\ntomorrow : {c+1}")





yestarday: 2024-01-17
today : 2024-01-18
tomorrow : 2024-01-19


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [141]:
start_date = np.datetime64('2016-01-01')
end_date = np.datetime64('2016-02-01')
vvv = np.arange(start_date, end_date, dtype='datetime64[D]')
print(vvv)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [143]:
x = np.random.randn(10)
print(x)
x = x[x>=0]
np.floor(x)

[ 1.2636202   0.47493571  0.83891565  0.8158484   0.782277   -2.03766538
 -0.48617295 -1.79484025 -0.89565169 -1.40106954]


array([1., 0., 0., 0., 0.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [150]:
a = np.random.randn(20)
print(a)
np.add.reduce(a)



[-0.83872304 -0.93771913 -1.05147428  1.15546292  0.53067107 -1.69462997
 -0.18498667  0.83524937  0.29133087  2.16585865  0.65147621 -0.75559822
  0.21265092  1.9994914  -1.36023699  0.29420216 -0.7736492   1.42605056
 -0.41354571 -0.39823597]


1.1536449442295764

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [158]:
original_vector = np.array([1, 2, 3, 4, 5])

modified_vector = np.zeros((len(original_vector), 4), dtype=int)

modified_vector[:, 0] = original_vector

print(modified_vector.flatten())


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [162]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14] )
b = np.array([a[i:i+4] for i in range(len(a)-3)])
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [165]:
a = np.array([1,2,3,4,5,6,7,8,9, 6,10,11, 8, 4, 5, 9, 1, 2, 2, 2 ,3,3,12,13,14])

print(np.unique(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`