In [1]:
import numpy as np

In [2]:
my_list = list(range(100000)) # python list 0~99999 --> Normal
my_array = np.array(range(100000)) # numpy array(massiv) 0~99999) --> vectorized

In [3]:
%time for _ in range(10): [x*2 for x in my_list] # normal

CPU times: user 76.7 ms, sys: 7.85 ms, total: 84.6 ms
Wall time: 88.1 ms


In [4]:
%time for _ in range(10): my_array*2 # vectorized

CPU times: user 2.65 ms, sys: 0 ns, total: 2.65 ms
Wall time: 6.6 ms


In [6]:
88.1/6.6


13.348484848484848

In [7]:
data1 = [3.5, 5, 6, 2] #list
arr1 = np.array(data1) #array1

In [8]:
arr1

array([3.5, 5. , 6. , 2. ])

In [9]:
data2 = (4, 5, 3.2, 7) #tuple
arr2= np.array(data2)


In [10]:
arr2

array([4. , 5. , 3.2, 7. ])

# Massiv size

In [12]:
arr1.ndim # size of array1

1

In [13]:
arr2.ndim # size of array2

1

# array of two or more

In [15]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] #nested list
arr3 = np.array(data3) #array3

In [17]:
arr3.ndim # size of arr3

2

# three-dimensional arrays.

In [21]:
data4 = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]]
arr4 = np.array(data4) #array4

In [22]:
arr4.ndim

3

# shape, size methods

In [23]:
arr4.shape # show number of row and columns

(2, 3, 4)

In [25]:
arr4.size

24

# Another method of creating an n-dimensional array.

1.   zeros
2.   ones
3.   arange



In [28]:
arr5 = np.zeros(shape =(2, 4)) # All elements are 0, 2x4 dimensional array
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
arr6 = np.ones((3, 6)) # All elements are 1, 3x6 dimensional array
arr6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [30]:
arr7 = np.arange(4,20,2)
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
arr8 = np.arange(20)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
import numpy as np

def one_dim(n):
    arr1 = np.arange(n)
    return arr1

for i in range(1, 10):
  assert len(one_dim(i)) == i, f"n elementlar soni, funksiyada noto'g'ri qo'llanilgan" # n number of elements
  arr = one_dim(i) # massiv
  assert arr.ndim == 1, f"1-o'lchamli massiv aniqlanmadi"#size of massiv
  assert type(arr) == np.ndarray, f"massiv aniqlanmadi" #numpy array

In [35]:
def two_dim(r, c):
    arr = np.zeros(shape =(r, c))

    return arr

arr = two_dim(5, 4) # massiv
assert arr.shape == (5, 4), f"funksiyada, o'lchamlar noto'g'ri qo'llanilgan" # shape
assert arr.ndim == 2, f"2-o'lchamli massiv aniqlanmadi" # size of massiv
assert type(arr) == np.ndarray, f"massiv aniqlanmadi"# #numpy array