<a href="https://colab.research.google.com/github/ChingizIbnVaxob/data-science-practices/blob/main/17.01.24/working_with__file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data.npy', arr)

In [5]:
arr2 = np.load('data.npy')

In [6]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1 = np.arange(20)

In [11]:
np.savez('arrays', a=arr, b=arr1)

In [12]:
arrays = np.load('arrays.npz')

In [13]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez_compressed('array_comp.npz', a=arr, b=arr1)

# Linear Algebra with Numpy!   (Simple!)
[Additional information.](https://towardsdatascience.com/introduction-to-linear-algebra-with-numpy-79adeb7bc060)

In [1]:
import numpy as np


In [2]:
x = np.array([[1.,2.,3.], [4.,5.,6.]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
y=np.array([[5.,5.,5.],[4.,4.,4.]])
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [19]:
x+y

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [20]:
y-x

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [21]:
x*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [22]:
y/x

array([[5.        , 2.5       , 1.66666667],
       [1.        , 0.8       , 0.66666667]])

In [24]:
z=np.array([[5.,5.],[4.,4.], [3.,3.]])
z

array([[5., 5.],
       [4., 4.],
       [3., 3.]])

In [25]:
x.dot(z)

array([[22., 22.],
       [58., 58.]])

In [26]:
np.dot(x,z)

array([[22., 22.],
       [58., 58.]])

In [27]:
z.dot(x)

array([[25., 35., 45.],
       [20., 28., 36.],
       [15., 21., 27.]])